# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SmartHome' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'

  # Pods for SmartHome

  pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'

  pod 'react-native-shake-event', :path => '../node_modules/react-native-shake-event'

  target 'SmartHomeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SmartHome-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SmartHome-tvOS

  target 'SmartHome-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
